name: (ðŸš€) => Publish

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: (ðŸ”º) Checkout
              uses: actions/checkout@v4

            - name: (ðŸ”º) Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: (ðŸ”º) Installing Dependencies...
              run: yarn install

            - name: (ðŸ”º) Building...
              run: |
                  yarn build

            - name: (ðŸ”º) Publishing... (NPM)
              run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: (ðŸ”º) Publishing... (GPR)
              run: |
                  yarn config set registry https://npm.pkg.github.com
                  yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
